const SVG_NS = 'http://www.w3.org/2000/svg';
const C = { navy:'#07345E', cyan:'#0B8793', pink:'#F36F3D', yellow:'#F59A0A', mint:'#438B63', blue:'#175E7C', text:'#30465A', muted:'#8A928F', line:'#DDE5E7', gray:'#B8C1C4' };

function clear(el){ el.innerHTML = ''; }
function svgEl(name, attrs={}) { const el = document.createElementNS(SVG_NS, name); Object.entries(attrs).forEach(([k,v]) => el.setAttribute(k,v)); return el; }
function makeSvg(container, viewBox='0 0 900 520') { clear(container); const svg = svgEl('svg', {viewBox, class:'chart-svg', role:'img', 'aria-label': container.dataset.label || 'Gráfico IDEB'}); container.appendChild(svg); return svg; }
function sx(v, min, max, left, width){ return left + ((v-min)/(max-min))*width; }
function sy(i, count, top, height){ return count <= 1 ? top + height/2 : top + (i/(count-1))*height; }
function showTip(evt, html){ const tip=document.querySelector('.tooltip'); tip.innerHTML=html; tip.style.left=`${evt.clientX+14}px`; tip.style.top=`${evt.clientY+14}px`; tip.style.opacity=1; }
function hideTip(){ const tip=document.querySelector('.tooltip'); if(tip) tip.style.opacity=0; }
function text(svg, x, y, content, attrs={}) { const t=svgEl('text', {x,y, ...attrs}); t.textContent=content; svg.appendChild(t); return t; }
function line(svg, x1,y1,x2,y2, attrs={}) { const l=svgEl('line', {x1,y1,x2,y2, ...attrs}); svg.appendChild(l); return l; }
function rect(svg, x,y,w,h, attrs={}) { const r=svgEl('rect', {x,y,width:w,height:h,rx:8, ...attrs}); svg.appendChild(r); return r; }
function circle(svg, cx,cy,r, attrs={}) { const c=svgEl('circle', {cx,cy,r, ...attrs}); svg.appendChild(c); return c; }
function path(svg, d, attrs={}) { const p=svgEl('path', {d, ...attrs}); svg.appendChild(p); return p; }
function grid(svg, left, top, width, height, max=10) { for(let v=0; v<=max; v+=2){ const x=sx(v,0,max,left,width); line(svg,x,top,x,top+height,{class:'grid-line'}); text(svg,x,top+height+28,String(v),{'text-anchor':'middle',class:'label'}); } }
function bindTip(el, html){ el.addEventListener('mousemove', e=>showTip(e, html)); el.addEventListener('mouseleave', hideTip); }

function renderSummaryBars(id){
  const svg=makeSvg(document.getElementById(id)); const rows=municipalityRows(); const left=58, top=48, width=790, height=390; grid(svg,left,top,width,height,10);
  const groups=rows; const barW=74; groups.forEach((r,i)=>{ const gx=left+190+i*340; const y23=top+height-(r.ideb_2023/10)*height; const y25=top+height-(r.ideb_2025/10)*height; const b1=rect(svg,gx,y23,barW,top+height-y23,{fill:C.navy}); const b2=rect(svg,gx+barW+16,y25,barW,top+height-y25,{fill:C.mint}); text(svg,gx+barW/2,y23-12,formatIdeb(r.ideb_2023),{'text-anchor':'middle',class:'value-label'}); text(svg,gx+barW+16+barW/2,y25-12,formatIdeb(r.ideb_2025),{'text-anchor':'middle',class:'value-label'}); text(svg,gx+barW+8,top+height+62,r.etapa,{'text-anchor':'middle',class:'label'}); bindTip(b1, `<strong>${r.etapa} — 2023</strong>IDEB: ${formatIdeb(r.ideb_2023)}`); bindTip(b2, `<strong>${r.etapa} — 2025</strong>IDEB: ${formatIdeb(r.ideb_2025)}<br>Variação: ${formatDelta(r.variacao_absoluta)}`); });
  text(svg,left,34,'IDEB em escala 0 a 10',{fill:C.muted,'font-size':16});
}

function renderDumbbell(id, stage){
  const svg=makeSvg(document.getElementById(id),'0 0 900 360'); const r=byStage(municipalityRows(),stage); const left=58, top=140, width=790; grid(svg,left,62,width,164,10);
  const x23=sx(r.ideb_2023,0,10,left,width), x25=sx(r.ideb_2025,0,10,left,width); line(svg,x23,top,x25,top,{stroke:C.line,'stroke-width':18,'stroke-linecap':'round'}); const c1=circle(svg,x23,top,35,{fill:C.navy}); const c2=circle(svg,x25,top,42,{fill:C.mint}); text(svg,x23,top+6,formatIdeb(r.ideb_2023),{'text-anchor':'middle',fill:'#fff','font-weight':900,'font-size':18}); text(svg,x25,top+6,formatIdeb(r.ideb_2025),{'text-anchor':'middle',fill:'#fff','font-weight':900,'font-size':20}); text(svg,x23,top+72,'2023',{'text-anchor':'middle',class:'label'}); text(svg,x25,top+78,'2025',{'text-anchor':'middle',class:'label'}); text(svg,(x23+x25)/2,top-55,`${formatDelta(r.variacao_absoluta)} ponto | ${formatPercent(r.variacao_percentual)}`,{'text-anchor':'middle',fill:C.mint,'font-weight':900,'font-size':22}); bindTip(c2, `<strong>${stage}</strong>IDEB 2023: ${formatIdeb(r.ideb_2023)}<br>IDEB 2025: ${formatIdeb(r.ideb_2025)}<br>Variação: ${formatDelta(r.variacao_absoluta)}<br>Crescimento: ${formatPercent(r.variacao_percentual)}`);
}

function renderSergipeCompare(id, stage){
  const svg=makeSvg(document.getElementById(id)); const left=58, top=48, width=790, height=390; grid(svg,left,top,width,height,10); [2023,2025].forEach((year,i)=>{ const gap=getGap(stage,year); const x=left+190+i*350; const vals=[{label:'Rosário',v:gap.rosario_ideb,c:C.navy},{label:'Sergipe',v:gap.sergipe_media_municipal,c:C.gray}]; vals.forEach((d,j)=>{ const y=top+height-(d.v/10)*height; const b=rect(svg,x+j*82,y,56,top+height-y,{fill:d.c}); text(svg,x+j*82+28,y-10,formatIdeb(d.v),{'text-anchor':'middle',class:'value-label'}); bindTip(b, `<strong>${d.label} — ${year}</strong>IDEB: ${formatIdeb(d.v)}`); }); text(svg,x+69,top+height+50,String(year),{'text-anchor':'middle',class:'label'}); }); text(svg,left,34,stage,{fill:C.navy,'font-size':20,'font-weight':900}); }

function renderGap(id){
  const svg=makeSvg(document.getElementById(id),'0 0 900 500'); const rows=window.IDEB_DATA.gaps.filter(d=>d.ano===2025); const left=145, top=84, width=620, rowH=160;
  rows.forEach((r,i)=>{ const y=top+i*rowH; text(svg,40,y+12,r.etapa,{fill:C.navy,'font-size':22,'font-weight':900}); const xS=sx(r.sergipe_media_municipal,0,10,left,width), xR=sx(r.rosario_ideb,0,10,left,width); line(svg,left,y+62,left+width,y+62,{stroke:C.line,'stroke-width':10,'stroke-linecap':'round'}); circle(svg,xS,y+62,24,{fill:C.gray}); circle(svg,xR,y+62,31,{fill:C.yellow}); text(svg,xS,y+105,`SE ${formatIdeb(r.sergipe_media_municipal)}`,{'text-anchor':'middle',class:'label'}); text(svg,xR,y+18,`Rosário ${formatIdeb(r.rosario_ideb)}`,{'text-anchor':'middle',fill:C.yellow,'font-size':15,'font-weight':900}); text(svg,760,y+68,formatDelta(r.gap_sergipe),{fill:r.gap_sergipe>=0?C.mint:C.pink,'font-size':30,'font-weight':900}); });
}

function renderDre4Ranking(id, stage='Anos Iniciais', year=2025){
  const svg=makeSvg(document.getElementById(id),'0 0 900 560'); const df=window.IDEB_DATA.dre4.filter(d=>d.etapa===stage && d.ano===year).sort((a,b)=>a.posicao-b.posicao); const left=188, top=30, width=650, rowH=52;
  df.forEach((d,i)=>{ const y=top+i*rowH; const w=(d.ideb/10)*width; const isR=d.id_municipio==='2806107'; const b=rect(svg,left,y,w,32,{fill:isR?C.yellow:C.navy,opacity:isR?1:.78}); text(svg,18,y+22,`${d.posicao}º`,{fill:isR?C.pink:C.muted,'font-weight':900,'font-size':15}); text(svg,55,y+22,d.municipio_dre4,{fill:isR?C.yellow:C.text,'font-weight':isR?900:600,'font-size':15}); text(svg,left+w+12,y+22,formatIdeb(d.ideb),{fill:C.navy,'font-weight':900,'font-size':15}); bindTip(b, `<strong>${d.municipio_dre4}</strong>${stage} — ${year}<br>IDEB: ${formatIdeb(d.ideb)}<br>Posição DRE 4: ${formatPosition(d.posicao)}`); });
}

function renderDre4Variation(id, stage='Anos Iniciais'){
  const svg=makeSvg(document.getElementById(id),'0 0 900 560'); const df=window.IDEB_DATA.dre4_variacao.filter(d=>d.etapa===stage && d.ideb_2023!==null && d.ideb_2025!==null).sort((a,b)=>a.variacao_absoluta-b.variacao_absoluta); const left=370, top=38, scale=285, rowH=54; line(svg,left,28,left,top+rowH*df.length,{stroke:C.text,'stroke-width':1}); df.forEach((d,i)=>{ const y=top+i*rowH; const v=d.variacao_absoluta; const x=v>=0?left:left+v*scale; const w=Math.abs(v*scale); const isR=d.id_municipio==='2806107'; const b=rect(svg,x,y,w,32,{fill:isR?C.yellow:(v>=0?C.mint:C.pink),opacity:isR?1:.78}); text(svg,30,y+22,d.municipio_dre4,{fill:isR?C.yellow:C.text,'font-weight':isR?900:600,'font-size':15}); text(svg,v>=0?left+w+12:x-12,y+22,formatDelta(v),{'text-anchor':v>=0?'start':'end',fill:C.navy,'font-weight':900,'font-size':15}); bindTip(b, `<strong>${d.municipio_dre4}</strong>${stage}<br>2023: ${formatIdeb(d.ideb_2023)}<br>2025: ${formatIdeb(d.ideb_2025)}<br>Variação: ${formatDelta(v)}`); });
}

function renderDre4Slope(id, stage='Anos Iniciais'){
  const svg=makeSvg(document.getElementById(id),'0 0 900 560'); const rows=window.IDEB_DATA.dre4_variacao.filter(d=>d.etapa===stage && d.ideb_2023!==null && d.ideb_2025!==null); const x1=150,x2=760,top=52,height=435; text(svg,x1,30,'2023',{'text-anchor':'middle',fill:C.navy,'font-weight':900}); text(svg,x2,30,'2025',{'text-anchor':'middle',fill:C.navy,'font-weight':900}); rows.forEach(d=>{ const y1=top+height-(d.ideb_2023/10)*height, y2=top+height-(d.ideb_2025/10)*height; const isR=d.id_municipio==='2806107'; const p=line(svg,x1,y1,x2,y2,{stroke:isR?C.yellow:C.gray,'stroke-width':isR?5:2,opacity:isR?1:.45}); circle(svg,x1,y1,isR?7:5,{fill:isR?C.yellow:C.gray}); circle(svg,x2,y2,isR?8:5,{fill:isR?C.yellow:C.gray}); if(isR){ text(svg,x2+18,y2+5,`Rosário ${formatIdeb(d.ideb_2025)}`,{fill:C.yellow,'font-weight':900}); } bindTip(p, `<strong>${d.municipio_dre4}</strong>${stage}<br>2023: ${formatIdeb(d.ideb_2023)}<br>2025: ${formatIdeb(d.ideb_2025)}<br>Variação: ${formatDelta(d.variacao_absoluta)}`); }); }

function renderFlow(id){
  const svg=makeSvg(document.getElementById(id),'0 0 900 500'); const rows=municipalityRows(); const left=92, top=64, width=735, gap=120; rows.forEach((r,i)=>{ const y=top+i*180; text(svg,30,y+42,r.etapa,{fill:C.navy,'font-size':20,'font-weight':900}); [['Desempenho',r.nota_saeb_media_padronizada_2023,r.nota_saeb_media_padronizada_2025,C.cyan],['Fluxo',r.indicador_rendimento_2023,r.indicador_rendimento_2025,C.mint]].forEach((m,j)=>{ const yy=y+j*72; const min=j?0.75:3.5, max=j?1:6; const x23=sx(m[1],min,max,left,width), x25=sx(m[2],min,max,left,width); line(svg,x23,yy,x25,yy,{stroke:C.line,'stroke-width':10,'stroke-linecap':'round'}); circle(svg,x23,yy,16,{fill:C.navy}); circle(svg,x25,yy,20,{fill:m[3]}); text(svg,left-12,yy+5,m[0],{'text-anchor':'end',fill:C.text,'font-size':14,'font-weight':800}); text(svg,x25+28,yy+5,`${fmt(m[2],j?3:1)} (${formatDelta(m[2]-m[1])})`,{fill:C.navy,'font-size':14,'font-weight':900}); }); }); }

function renderSchoolsTable(status='Todas'){
  const tbody=document.querySelector('#schools-table tbody'); tbody.innerHTML=''; const rows=window.IDEB_DATA.escolas.filter(r=>status==='Todas'||r.status===status).sort((a,b)=>b.variacao_absoluta-a.variacao_absoluta); rows.forEach(r=>{ const tr=document.createElement('tr'); tr.innerHTML=`<td>${shortSchool(r.escola)}</td><td>${r.etapa}</td><td>${formatIdeb(r.ideb_2023)}</td><td>${formatIdeb(r.ideb_2025)}</td><td><strong>${formatDelta(r.variacao_absoluta)}</strong></td>`; tbody.appendChild(tr); }); }

function renderSchoolDumbbell(id){
  const svg=makeSvg(document.getElementById(id),'0 0 900 560'); const df=[...window.IDEB_DATA.escolas].sort((a,b)=>a.ideb_2025-b.ideb_2025); const left=255, top=52, width=585, rowH=80; df.forEach((d,i)=>{ const y=top+i*rowH; const x23=sx(d.ideb_2023,0,10,left,width), x25=sx(d.ideb_2025,0,10,left,width); line(svg,x23,y,x25,y,{stroke:C.line,'stroke-width':8,'stroke-linecap':'round'}); circle(svg,x23,y,13,{fill:C.navy}); const c=circle(svg,x25,y,17,{fill:C.mint}); text(svg,18,y+5,shortSchool(d.escola).slice(0,34),{fill:C.text,'font-size':13,'font-weight':700}); text(svg,left+width+18,y+5,formatIdeb(d.ideb_2025),{fill:C.navy,'font-weight':900}); bindTip(c, `<strong>${shortSchool(d.escola)}</strong>${d.etapa}<br>IDEB 2023: ${formatIdeb(d.ideb_2023)}<br>IDEB 2025: ${formatIdeb(d.ideb_2025)}<br>Variação: ${formatDelta(d.variacao_absoluta)}<br>Crescimento: ${formatPercent(d.variacao_percentual)}`); }); }

function renderSchoolVariation(id){
  const svg=makeSvg(document.getElementById(id),'0 0 900 560'); const df=[...window.IDEB_DATA.escolas].sort((a,b)=>a.variacao_absoluta-b.variacao_absoluta); const left=295, top=52, scale=330, rowH=80; line(svg,left,35,left,top+rowH*df.length,{stroke:C.text,'stroke-width':1}); df.forEach((d,i)=>{ const y=top+i*rowH; const w=Math.abs(d.variacao_absoluta*scale); const b=rect(svg,left,y,w,34,{fill:d.variacao_absoluta>=0?C.mint:C.pink}); text(svg,18,y+22,`${d.etapa.replace('Anos ','')} | ${shortSchool(d.escola).slice(0,28)}`,{fill:C.text,'font-size':13,'font-weight':700}); text(svg,left+w+14,y+23,formatDelta(d.variacao_absoluta),{fill:C.navy,'font-weight':900}); bindTip(b, `<strong>${shortSchool(d.escola)}</strong>${d.etapa}<br>Variação: ${formatDelta(d.variacao_absoluta)}<br>Crescimento: ${formatPercent(d.variacao_percentual)}`); }); }


