const state = { sergipeStage:'Anos Iniciais', dre4Stage:'Anos Iniciais', dre4Year:2025, dre4VarStage:'Anos Iniciais', slopeStage:'Anos Iniciais' };
function kpi(label,value,note,color='white',digits=1){ const isColor=color!=='white'; return `<div class="kpi-card ${isColor?'color':''}" style="${isColor?`background:var(--${color})`:''}"><div class="kpi-label">${label}</div><div class="kpi-value counter-number" data-value="${value}" data-digits="${digits}">0</div><div class="kpi-note">${note}</div></div>`; }
function staticKpi(label,value,note,color='white'){ const isColor=color!=='white'; return `<div class="kpi-card ${isColor?'color':''}" style="${isColor?`background:var(--${color})`:''}"><div class="kpi-label">${label}</div><div class="kpi-value">${value}</div><div class="kpi-note">${note}</div></div>`; }
function renderStaticContent(){
  const rows=stageOrder.map(stage => byStage(municipalityRows(), stage)); const ini=byStage(rows,'Anos Iniciais'), fin=byStage(rows,'Anos Finais');
  document.getElementById('summary-kpis').innerHTML = [
    kpi('IDEB 2025',ini.ideb_2025,'Anos Iniciais','cyan'), kpi('IDEB 2025',fin.ideb_2025,'Anos Finais','navy'),
    kpi('Variação',ini.variacao_absoluta,'Anos Iniciais','mint'), kpi('Variação',fin.variacao_absoluta,'Anos Finais','pink'),
    staticKpi('Posição DRE 4',formatPosition(ini.posicao_dre4_2025),'Anos Iniciais','yellow'), staticKpi('Posição DRE 4',formatPosition(fin.posicao_dre4_2025),'Anos Finais','cyan')
  ].join('');
  document.getElementById('change-subtitle').textContent = `${variationPhrase(ini)} ${variationPhrase(fin)}`;
  document.getElementById('change-visual').innerHTML = rows.map(r=>`<article class="change-card"><div><div class="change-stage">${r.etapa}</div><div class="change-year">2023</div><div class="change-value">${formatIdeb(r.ideb_2023)}</div></div><div class="change-arrow">?</div><div><div class="change-year">2025</div><div class="change-value current">${formatIdeb(r.ideb_2025)}</div></div><div class="change-delta">${formatDelta(r.variacao_absoluta)} ponto<small>${formatPercent(r.variacao_percentual)} no per?odo</small></div></article>`).join('');
  document.getElementById('title-iniciais').textContent = `Rosário avança ${formatDelta(ini.variacao_absoluta)} ponto nos anos iniciais`;
  document.getElementById('title-finais').textContent = `Rosário avança ${formatDelta(fin.variacao_absoluta)} ponto nos anos finais`;
  document.getElementById('insight-iniciais').innerHTML = `${variationPhrase(ini)}<small>${dre4PositionPhrase(ini)}</small>`;
  document.getElementById('insight-finais').innerHTML = `${variationPhrase(fin)}<small>${dre4PositionPhrase(fin)}</small>`;
  document.getElementById('dre4-position-cards').innerHTML = rows.map(r=>staticKpi(r.etapa, `${formatPosition(r.posicao_dre4_2023)} → ${formatPosition(r.posicao_dre4_2025)}`, dre4PositionPhrase(r), r.etapa.includes('Iniciais')?'cyan':'pink')).join('');
  document.getElementById('flow-kpis').innerHTML = rows.flatMap(r=>[staticKpi(`Desempenho · ${r.etapa}`,formatIdeb(r.nota_saeb_media_padronizada_2025),'Nota média padronizada 2025',r.etapa.includes('Iniciais')?'navy':'pink'), staticKpi(`Fluxo · ${r.etapa}`,fmt(r.indicador_rendimento_2025,3),'Indicador de rendimento 2025',r.etapa.includes('Iniciais')?'cyan':'yellow')]).join('');
  document.getElementById('flow-insight').innerHTML = rows.map(driverPhrase).join('<br><br>');
  renderSchoolsTable('Todas');
  document.getElementById('school-var-title').textContent = `${window.IDEB_DATA.indicadores.escolas_avancaram} resultados escolares avançaram`;
  const best=window.IDEB_DATA.indicadores.maior_avanco_escola; document.getElementById('school-var-insight').innerHTML = `Maior avanço: ${shortSchool(best.escola)}<small>${best.etapa} · ${formatDelta(best.variacao_absoluta)} ponto</small>`;
  renderSchoolMatrix(); renderDiagnosis(); renderPriorities(); renderFinalIndicators(); setupControls();
}
function renderSchoolMatrix(){ const ind=window.IDEB_DATA.indicadores; const cats=[['Avançaram','Avancaram',ind.escolas_avancaram,'mint'],['Estáveis','Estaveis',ind.escolas_estaveis,'yellow'],['Recuaram','Recuaram',ind.escolas_recuaram,'pink']]; document.getElementById('school-matrix').innerHTML=cats.map(c=>`<div class="kpi-card matrix-card color" data-cat="${c[1]}" style="background:var(--${c[3]})"><div class="kpi-label">${c[0]}</div><div class="kpi-value">${c[2]}</div><div class="kpi-note">resultados escolares</div></div>`).join(''); document.querySelectorAll('.matrix-card').forEach(card=>card.onclick=()=>{ const cat=card.dataset.cat; const list=window.IDEB_DATA.escolas.filter(e=>e.status===cat).map(e=>`<strong>${shortSchool(e.escola)}</strong> · ${e.etapa} (${formatDelta(e.variacao_absoluta)})`).join('<br>') || 'Nenhuma escola nesta categoria.'; document.getElementById('school-list').innerHTML=list; }); }
function renderDiagnosis(){ const cols=[['Avanços',positiveHighlights().slice(0,3),'mint'],['Pontos de atenção',attentionPoints(),'pink'],['Oportunidades',priorities().slice(0,3),'yellow']]; document.getElementById('diagnosis-cols').innerHTML=cols.map(c=>`<div class="card dimension-card"><div class="eyebrow" style="color:var(--${c[2]})">${c[0]}</div>${c[1].map(i=>`<p style="margin:0 0 14px">${i}</p>`).join('')}</div>`).join(''); }
function renderPriorities(){ document.getElementById('priorities-list').innerHTML=priorities().map((p,i)=>`${i+1}. ${p}`).join('<br><br>'); }
function renderFinalIndicators(){ const ini=byStage(municipalityRows(),'Anos Iniciais'), fin=byStage(municipalityRows(),'Anos Finais'); document.getElementById('final-indicators').innerHTML=[staticKpi('IDEB iniciais',formatIdeb(ini.ideb_2025),`${formatDelta(ini.variacao_absoluta)} ponto`,'cyan'),staticKpi('IDEB finais',formatIdeb(fin.ideb_2025),`${formatDelta(fin.variacao_absoluta)} ponto`,'navy'),staticKpi('DRE 4 iniciais',formatPosition(ini.posicao_dre4_2025),'posição 2025','pink'),staticKpi('Escolas avançaram',String(window.IDEB_DATA.indicadores.escolas_avancaram),`de ${window.IDEB_DATA.indicadores.total_escolas_comparaveis} comparáveis`,'mint')].join(''); }
function setupControls(){
  document.querySelectorAll('[data-stage-control="sergipe"] button').forEach(btn=>btn.onclick=()=>{ setActive(btn); state.sergipeStage=btn.dataset.stage; renderSergipeSlide(); });
  document.querySelectorAll('[data-stage-control="dre4"] button[data-stage]').forEach(btn=>btn.onclick=()=>{ setActive(btn,'[data-stage-control="dre4"] button[data-stage]'); state.dre4Stage=btn.dataset.stage; renderDre4Slide(); });
  document.querySelectorAll('[data-stage-control="dre4"] button[data-year]').forEach(btn=>btn.onclick=()=>{ setActive(btn,'[data-stage-control="dre4"] button[data-year]'); state.dre4Year=Number(btn.dataset.year); renderDre4Slide(); });
  document.querySelectorAll('[data-stage-control="dre4var"] button').forEach(btn=>btn.onclick=()=>{ setActive(btn); state.dre4VarStage=btn.dataset.stage; renderDre4VarSlide(); });
  document.querySelectorAll('[data-stage-control="slope"] button').forEach(btn=>btn.onclick=()=>{ setActive(btn); state.slopeStage=btn.dataset.stage; renderDre4SlopeSlide(); });
  document.querySelectorAll('#school-filters button').forEach(btn=>btn.onclick=()=>{ setActive(btn); renderSchoolsTable(btn.dataset.status); });
}
function setActive(btn, selector=null){ const parent=btn.parentElement; (selector?document.querySelectorAll(selector):parent.querySelectorAll('button')).forEach(b=>b.classList.remove('active')); btn.classList.add('active'); }
function renderSergipeSlide(){ renderSergipeCompare('chart-sergipe',state.sergipeStage); document.getElementById('sergipe-title').textContent=state.sergipeStage+': comparação com Sergipe'; document.getElementById('sergipe-insight').innerHTML=gapPhrase(state.sergipeStage)+'<small>Sergipe = média municipal dos municípios disponíveis.</small>'; }
function renderDre4Slide(){ renderDre4Ranking('chart-dre4-ranking',state.dre4Stage,state.dre4Year); const ros=window.IDEB_DATA.dre4.find(d=>d.etapa===state.dre4Stage&&d.ano===state.dre4Year&&d.id_municipio==='2806107'); document.getElementById('dre4-ranking-title').textContent = ros ? `Rosário ocupa a ${formatPosition(ros.posicao)} posição da DRE 4 em ${state.dre4Year}` : 'Rosário sem resultado disponível na seleção'; document.getElementById('dre4-ranking-insight').innerHTML = ros ? `${state.dre4Stage}: IDEB ${formatIdeb(ros.ideb)}<small>Rosário está destacado em magenta.</small>` : 'Sem resultado disponível.'; }
function renderDre4VarSlide(){ renderDre4Variation('chart-dre4-var',state.dre4VarStage); const ros=window.IDEB_DATA.dre4_variacao.find(d=>d.etapa===state.dre4VarStage&&d.id_municipio==='2806107'); document.getElementById('dre4-var-insight').innerHTML = `Rosário: ${formatDelta(ros.variacao_absoluta)} ponto<small>${state.dre4VarStage} · 2023 → 2025</small>`; }
function renderDre4SlopeSlide(){ renderDre4Slope('chart-dre4-slope',state.slopeStage); }
function renderSlideCharts(slide){ const r=slide.dataset.render; if(r==='summary') document.querySelectorAll('.counter-number').forEach(animateNumber); if(r==='dumbbell-iniciais') renderDumbbell('chart-iniciais','Anos Iniciais'); if(r==='dumbbell-finais') renderDumbbell('chart-finais','Anos Finais'); if(r==='summary-bars') renderSummaryBars('chart-summary-bars'); if(r==='sergipe') renderSergipeSlide(); if(r==='gap') renderGap('chart-gap'); if(r==='dre4-ranking') renderDre4Slide(); if(r==='dre4-variation') renderDre4VarSlide(); if(r==='dre4-slope') renderDre4SlopeSlide(); if(r==='flow') renderFlow('chart-flow'); if(r==='school-dumbbell') renderSchoolDumbbell('chart-school-dumbbell'); if(r==='school-var') renderSchoolVariation('chart-school-var'); }
document.addEventListener('DOMContentLoaded',()=>{ renderStaticContent(); initNavigation(); });
